//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekart.LazyNet {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dekart.LazyNet.ConstStrings", typeof(ConstStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;image=#UISuperHero&gt;&lt;br&gt;&lt;color=#{0:x6}&gt;&lt;size=+24&gt;Стань Супергероем офиса&lt;br&gt;&lt;color=#{0:x6}&gt;&lt;size=-18&gt;Посмотри сколько полезных программ мы для тебя сделали&lt;br&gt;.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контроль доступа.
        /// </summary>
        public static string AccessControl {
            get {
                return ResourceManager.GetString("AccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения свойств из Active Directory.
        /// </summary>
        public static string ActiveDirectoryReadError {
            get {
                return ResourceManager.GetString("ActiveDirectoryReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВЛЕНО:{0:n0} ИЗ {1:n0}.
        /// </summary>
        public static string AddDeviceText {
            get {
                return ResourceManager.GetString("AddDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;br&gt;&lt;br&gt;Address: &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string AddressHtml {
            get {
                return ResourceManager.GetString("AddressHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Все].
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All files (*.*)|*.*.
        /// </summary>
        public static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;br&gt;Birth Date: &lt;b&gt;{0:d}&lt;/b&gt;.
        /// </summary>
        public static string BirthDateHtml {
            get {
                return ResourceManager.GetString("BirthDateHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАГРУЖЕНО {0:n0} ИЗ {1:n0} БАЙТ.
        /// </summary>
        public static string BytesDownloadedText {
            get {
                return ResourceManager.GetString("BytesDownloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить изображение.
        /// </summary>
        public static string ClearImage {
            get {
                return ResourceManager.GetString("ClearImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть все открытые окна свойств.
        /// </summary>
        public static string CloseAllOpenDetailViews {
            get {
                return ResourceManager.GetString("CloseAllOpenDetailViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некоторые формы содержат изменения. Хотите закрыть эти формы?.
        /// </summary>
        public static string CloseCancelFormsWarning {
            get {
                return ResourceManager.GetString("CloseCancelFormsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите сохранить изменения?.
        /// </summary>
        public static string CloseCancelFormWarning {
            get {
                return ResourceManager.GetString("CloseCancelFormWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть текущий поиск..
        /// </summary>
        public static string CloseSearchDescription {
            get {
                return ResourceManager.GetString("CloseSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разобрать по копиям.
        /// </summary>
        public static string Collated {
            get {
                return ResourceManager.GetString("Collated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1,2,3   1,2,3  1,2,3.
        /// </summary>
        public static string CollatedDescription {
            get {
                return ResourceManager.GetString("CollatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компьютер.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВЛЕНО: {0:g}.
        /// </summary>
        public static string CreatedOnCaption {
            get {
                return ResourceManager.GetString("CreatedOnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CSV files (*.csv)|*.csv.
        /// </summary>
        public static string CSVFilter {
            get {
                return ResourceManager.GetString("CSVFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользовательские.
        /// </summary>
        public static string CustomFiltersName {
            get {
                return ResourceManager.GetString("CustomFiltersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выделенные записи.
        /// </summary>
        public static string DeleteButtonHint {
            get {
                return ResourceManager.GetString("DeleteButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DeleteFilter {
            get {
                return ResourceManager.GetString("DeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить {0}?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УСТРОЙСТВ:{0:n0}.
        /// </summary>
        public static string DeviceCountText {
            get {
                return ResourceManager.GetString("DeviceCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОСКАНИРОВАНО:{0:n0} ИЗ {1:n0}.
        /// </summary>
        public static string DeviceFindText {
            get {
                return ResourceManager.GetString("DeviceFindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройства.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать выделенный {0}.
        /// </summary>
        public static string EditButtonHint {
            get {
                return ResourceManager.GetString("EditButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string EditFilter {
            get {
                return ResourceManager.GetString("EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;br&gt;Email: &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string EmailHtml {
            get {
                return ResourceManager.GetString("EmailHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортировать отчет {0}.
        /// </summary>
        public static string ExportButtonHint {
            get {
                return ResourceManager.GetString("ExportButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт отчета.
        /// </summary>
        public static string ExportButtonHintDefault {
            get {
                return ResourceManager.GetString("ExportButtonHintDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных в различные форматы файлов.
        /// </summary>
        public static string ExportDescription {
            get {
                return ResourceManager.GetString("ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при экспорте.
        /// </summary>
        public static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите открыть этот файл?.
        /// </summary>
        public static string ExportFileOpen {
            get {
                return ResourceManager.GetString("ExportFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в HTML.
        /// </summary>
        public static string ExportToHTML {
            get {
                return ResourceManager.GetString("ExportToHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в Image.
        /// </summary>
        public static string ExportToImage {
            get {
                return ResourceManager.GetString("ExportToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в MHT.
        /// </summary>
        public static string ExportToMHT {
            get {
                return ResourceManager.GetString("ExportToMHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в PDF.
        /// </summary>
        public static string ExportToPDF {
            get {
                return ResourceManager.GetString("ExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в RTF.
        /// </summary>
        public static string ExportToRTF {
            get {
                return ResourceManager.GetString("ExportToRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в текст.
        /// </summary>
        public static string ExportToText {
            get {
                return ResourceManager.GetString("ExportToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в XLS.
        /// </summary>
        public static string ExportToXLS {
            get {
                return ResourceManager.GetString("ExportToXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в XLSX.
        /// </summary>
        public static string ExportToXLSX {
            get {
                return ResourceManager.GetString("ExportToXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в XML.
        /// </summary>
        public static string ExportToXML {
            get {
                return ResourceManager.GetString("ExportToXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти устройства.
        /// </summary>
        public static string FindButtonCaption {
            get {
                return ResourceManager.GetString("FindButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить поиск.
        /// </summary>
        public static string FindButtonCaptionStop {
            get {
                return ResourceManager.GetString("FindButtonCaptionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск останавливается.
        /// </summary>
        public static string FindButtonCaptionStopPending {
            get {
                return ResourceManager.GetString("FindButtonCaptionStopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группы.
        /// </summary>
        public static string GroupFiltersName {
            get {
                return ResourceManager.GetString("GroupFiltersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГЛАВНАЯ.
        /// </summary>
        public static string HomePageText {
            get {
                return ResourceManager.GetString("HomePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HTML files (*.html)|*.html.
        /// </summary>
        public static string HTMLFilter {
            get {
                return ResourceManager.GetString("HTMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HTML Документ (*.html)|*.html.
        /// </summary>
        public static string HTMLOpenFileFilter {
            get {
                return ResourceManager.GetString("HTMLOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BMP files (*.bmp)|*.bmp|Gif files (*.gif)|*.gif|Jpeg files (*.jpeg)|*.jpeg|PNG files (*.png)|*.png|Tiff files (*.tiff)|*.tiff|EMF files (*.emf)|.emf|WMF files (*.wmf)|*.wmf.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОБЪЕКТОВ: {0}.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутрення ошибка.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - Not valid property..
        /// </summary>
        public static string InvalidPropertyError {
            get {
                return ResourceManager.GetString("InvalidPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ранее в этом месяце.
        /// </summary>
        public static string IsEarlierThisMonth {
            get {
                return ResourceManager.GetString("IsEarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ранее на этой неделе.
        /// </summary>
        public static string IsEarlierThisWeek {
            get {
                return ResourceManager.GetString("IsEarlierThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ранее в этом году.
        /// </summary>
        public static string IsEarlierThisYear {
            get {
                return ResourceManager.GetString("IsEarlierThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На прошлой неделе.
        /// </summary>
        public static string IsLastWeek {
            get {
                return ResourceManager.GetString("IsLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        public static string IsToday {
            get {
                return ResourceManager.GetString("IsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вчера.
        /// </summary>
        public static string IsYesterday {
            get {
                return ResourceManager.GetString("IsYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Альбомная ориентация.
        /// </summary>
        public static string LandscapeOrientation {
            get {
                return ResourceManager.GetString("LandscapeOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект нельзя сохранить. Он был изменен или удален (очищен) другим приложением..
        /// </summary>
        public static string LockingExceptionError {
            get {
                return ResourceManager.GetString("LockingExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОБРАБОТАНО ПРОИЗВОДИТЕЛЕЙ {0:n0} ИЗ {1:n0}.
        /// </summary>
        public static string ManufacturersImportedText {
            get {
                return ResourceManager.GetString("ManufacturersImportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НЕИЗВЕСТНЫЙ ПРОИЗВОДИТЕЛЬ.
        /// </summary>
        public static string ManufacturerUnknown {
            get {
                return ResourceManager.GetString("ManufacturerUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планы.
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Умеренные поля.
        /// </summary>
        public static string MarginsModerate {
            get {
                return ResourceManager.GetString("MarginsModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верх:	25 mm	Низ:	25 mm
        ///Лево:	19 mm	Право:	19 mm.
        /// </summary>
        public static string MarginsModerateDescription {
            get {
                return ResourceManager.GetString("MarginsModerateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узкие поля.
        /// </summary>
        public static string MarginsNarrow {
            get {
                return ResourceManager.GetString("MarginsNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верх:	12 mm	Низ:	12 mm
        ///Лево:	12 mm	Право:	12 mm.
        /// </summary>
        public static string MarginsNarrowDescription {
            get {
                return ResourceManager.GetString("MarginsNarrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормальные поля.
        /// </summary>
        public static string MarginsNormal {
            get {
                return ResourceManager.GetString("MarginsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верх:	25 mm	Низ:	25 mm
        ///Лево:	25 mm	Право:	25 mm.
        /// </summary>
        public static string MarginsNormalDescription {
            get {
                return ResourceManager.GetString("MarginsNormalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широкие поля.
        /// </summary>
        public static string MarginsWide {
            get {
                return ResourceManager.GetString("MarginsWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верх:	25 mm	Низ:	25 mm
        ///Лево:	50 mm	Право:	50 mm.
        /// </summary>
        public static string MarginsWideDescription {
            get {
                return ResourceManager.GetString("MarginsWideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заметка.
        /// </summary>
        public static string MemoStyleString {
            get {
                return ResourceManager.GetString("MemoStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MHT files (*.mht)|*.mht.
        /// </summary>
        public static string MHTFilter {
            get {
                return ResourceManager.GetString("MHTFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MHT Документ (*.mht)|*.mht.
        /// </summary>
        public static string MHTOpenFileFilter {
            get {
                return ResourceManager.GetString("MHTOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разное.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильное устройство.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Монитор.
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить устройство из {0} в {1}?.
        /// </summary>
        public static string MoveDeviceQuestion {
            get {
                return ResourceManager.GetString("MoveDeviceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещения.
        /// </summary>
        public static string Movements {
            get {
                return ResourceManager.GetString("Movements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переключение между модулями..
        /// </summary>
        public static string NavigationDescription {
            get {
                return ResourceManager.GetString("NavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed because:.
        /// </summary>
        public static string NetError {
            get {
                return ResourceManager.GetString("NetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сетевое оборудование.
        /// </summary>
        public static string Networking {
            get {
                return ResourceManager.GetString("Networking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string NewFilter {
            get {
                return ResourceManager.GetString("NewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First.
        /// </summary>
        public static string NewFirstName {
            get {
                return ResourceManager.GetString("NewFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last.
        /// </summary>
        public static string NewLastName {
            get {
                return ResourceManager.GetString("NewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая карта.
        /// </summary>
        public static string NewMap {
            get {
                return ResourceManager.GetString("NewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое помещение.
        /// </summary>
        public static string NewRoom {
            get {
                return ResourceManager.GetString("NewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое программное обеспечение.
        /// </summary>
        public static string NewSoftware {
            get {
                return ResourceManager.GetString("NewSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый сотрудник.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступна новая версия: {0}
        ///Текущая версия: {1}.
        /// </summary>
        public static string NotificationBody {
            get {
                return ResourceManager.GetString("NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите для установки.
        /// </summary>
        public static string NotificationBody2 {
            get {
                return ResourceManager.GetString("NotificationBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот объект не может быть удален.
        /// </summary>
        public static string ObjectCanNotBeDeleted {
            get {
                return ResourceManager.GetString("ObjectCanNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонняя печать.
        /// </summary>
        public static string OneSide {
            get {
                return ResourceManager.GetString("OneSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печатать только на одной стороне страницы.
        /// </summary>
        public static string OneSideDescription {
            get {
                return ResourceManager.GetString("OneSideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стр. {0} из .
        /// </summary>
        public static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A3.
        /// </summary>
        public static string PaperKindA3 {
            get {
                return ResourceManager.GetString("PaperKindA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 296 mm x 420 mm.
        /// </summary>
        public static string PaperKindA3Description {
            get {
                return ResourceManager.GetString("PaperKindA3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A4.
        /// </summary>
        public static string PaperKindA4 {
            get {
                return ResourceManager.GetString("PaperKindA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 210 mm x 296 mm.
        /// </summary>
        public static string PaperKindA4Description {
            get {
                return ResourceManager.GetString("PaperKindA4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A5.
        /// </summary>
        public static string PaperKindA5 {
            get {
                return ResourceManager.GetString("PaperKindA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 148 mm x 210 mm.
        /// </summary>
        public static string PaperKindA5Description {
            get {
                return ResourceManager.GetString("PaperKindA5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A6.
        /// </summary>
        public static string PaperKindA6 {
            get {
                return ResourceManager.GetString("PaperKindA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 105 mm x 148 mm.
        /// </summary>
        public static string PaperKindA6Description {
            get {
                return ResourceManager.GetString("PaperKindA6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Executive.
        /// </summary>
        public static string PaperKindExecutive {
            get {
                return ResourceManager.GetString("PaperKindExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 184 mm x 266 mm.
        /// </summary>
        public static string PaperKindExecutiveDescription {
            get {
                return ResourceManager.GetString("PaperKindExecutiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Legal.
        /// </summary>
        public static string PaperKindLegal {
            get {
                return ResourceManager.GetString("PaperKindLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 215 mm x 355 mm.
        /// </summary>
        public static string PaperKindLegalDescription {
            get {
                return ResourceManager.GetString("PaperKindLegalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Letter.
        /// </summary>
        public static string PaperKindLetter {
            get {
                return ResourceManager.GetString("PaperKindLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 215 mm x 279 mm.
        /// </summary>
        public static string PaperKindLetterDescription {
            get {
                return ResourceManager.GetString("PaperKindLetterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tabloid.
        /// </summary>
        public static string PaperKindTabloid {
            get {
                return ResourceManager.GetString("PaperKindTabloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 279 mm x 431 mm.
        /// </summary>
        public static string PaperKindTabloidDescription {
            get {
                return ResourceManager.GetString("PaperKindTabloidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PDF files (*.pdf)|*.pdf.
        /// </summary>
        public static string PDFFilter {
            get {
                return ResourceManager.GetString("PDFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PDF Документ (*.pdf)|*.pdf.
        /// </summary>
        public static string PDFOpenFileFilter {
            get {
                return ResourceManager.GetString("PDFOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;br&gt;Phone: &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string PhoneHtml {
            get {
                return ResourceManager.GetString("PhoneHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PNG Изображение (*.png)|*.png.
        /// </summary>
        public static string PNGOpenFileFilter {
            get {
                return ResourceManager.GetString("PNGOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Книжная ориентация.
        /// </summary>
        public static string PortraitOrientation {
            get {
                return ResourceManager.GetString("PortraitOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принтер.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сформировать отчет {0}.
        /// </summary>
        public static string PrintPreviewButtonHint {
            get {
                return ResourceManager.GetString("PrintPreviewButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предварительный просмотр отчета ....
        /// </summary>
        public static string PrintPreviewDescription {
            get {
                return ResourceManager.GetString("PrintPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подождите.
        /// </summary>
        public static string ProgressPanelCaption {
            get {
                return ResourceManager.GetString("ProgressPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняется загрузка ....
        /// </summary>
        public static string ProgressPanelDescription {
            get {
                return ResourceManager.GetString("ProgressPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick Reports.
        /// </summary>
        public static string QuickReports {
            get {
                return ResourceManager.GetString("QuickReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ремонты и обслуживания.
        /// </summary>
        public static string Repairs {
            get {
                return ResourceManager.GetString("Repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файлы отчетов (*.repx)|*.repx|Все файлы (*.*)|*.*.
        /// </summary>
        public static string ReportFilter {
            get {
                return ResourceManager.GetString("ReportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - Изображение не найдено в ресурсах..
        /// </summary>
        public static string ResourceImageNotFoundError {
            get {
                return ResourceManager.GetString("ResourceImageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RTF files (*.rtf)|*.rtf.
        /// </summary>
        public static string RTFFilter {
            get {
                return ResourceManager.GetString("RTFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это значение не может быть пустым.
        /// </summary>
        public static string RuleIsNotBlankWarning {
            get {
                return ResourceManager.GetString("RuleIsNotBlankWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP адрес {0} уже назначен устройству {1}.
        /// </summary>
        public static string RuleUniqueIPAddressWarning {
            get {
                return ResourceManager.GetString("RuleUniqueIPAddressWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это значение должно быть уникальным и не пустым.
        /// </summary>
        public static string RuleUniqueNamesWarning {
            get {
                return ResourceManager.GetString("RuleUniqueNamesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серийный номер {0} уже назначен устройству {1}.
        /// </summary>
        public static string RuleUniqueSerialWarning {
            get {
                return ResourceManager.GetString("RuleUniqueSerialWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвентарный номер {0} уже назначен устройству {1}.
        /// </summary>
        public static string RuleUniqueSKUWarning {
            get {
                return ResourceManager.GetString("RuleUniqueSKUWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на run job failure.
        /// </summary>
        public static string RunJobFailure {
            get {
                return ResourceManager.GetString("RunJobFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо сохранить изменения! Продолжить?.
        /// </summary>
        public static string SaveCancelFormWarning {
            get {
                return ResourceManager.GetString("SaveCancelFormWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить фильтр..
        /// </summary>
        public static string SearchClearDescription {
            get {
                return ResourceManager.GetString("SearchClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть закладку поиска..
        /// </summary>
        public static string SearchCloseDescription {
            get {
                return ResourceManager.GetString("SearchCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите колонки, по которым будет производиться поиск..
        /// </summary>
        public static string SearchColumnsDescription {
            get {
                return ResourceManager.GetString("SearchColumnsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтровать устройства по дате покупки.
        /// </summary>
        public static string SearchCreatedDescription {
            get {
                return ResourceManager.GetString("SearchCreatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат к стандартному списку колонок для поиска..
        /// </summary>
        public static string SearchResetDescription {
            get {
                return ResourceManager.GetString("SearchResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск в папке &quot;{0}&quot; (Ctrl +E).
        /// </summary>
        public static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программное обеспечение.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск приложения.
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Избранное.
        /// </summary>
        public static string StaticFiltersName {
            get {
                return ResourceManager.GetString("StaticFiltersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица.
        /// </summary>
        public static string TableStyleString {
            get {
                return ResourceManager.GetString("TableStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text files (*.txt)|*.txt.
        /// </summary>
        public static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать вручную на обеих сторонах.
        /// </summary>
        public static string TwoSide {
            get {
                return ResourceManager.GetString("TwoSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузите бумагу, когда система предложит напечатать вторую сторону.
        /// </summary>
        public static string TwoSideDescription {
            get {
                return ResourceManager.GetString("TwoSideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обычный порядок.
        /// </summary>
        public static string Uncollated {
            get {
                return ResourceManager.GetString("Uncollated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1,1,1  2,2,2  3,3,3.
        /// </summary>
        public static string UncollatedDescription {
            get {
                return ResourceManager.GetString("UncollatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОБНОВЛЕНО: {0:g}.
        /// </summary>
        public static string UpdatedOnCaption {
            get {
                return ResourceManager.GetString("UpdatedOnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный пароль. Проверьте регистр клавиатуры и попробуйте еще раз..
        /// </summary>
        public static string UserInvalidPasswordError {
            get {
                return ResourceManager.GetString("UserInvalidPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указано имя пользователя..
        /// </summary>
        public static string UserNameEmptyError {
            get {
                return ResourceManager.GetString("UserNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - Пользователь не зарегистрирован..
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан пароль..
        /// </summary>
        public static string UserPasswordEmptyError {
            get {
                return ResourceManager.GetString("UserPasswordEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Люди.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - Пользователь уволен..
        /// </summary>
        public static string UserTerminatedError {
            get {
                return ResourceManager.GetString("UserTerminatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видеонаблюдение.
        /// </summary>
        public static string VideoSurveillance {
            get {
                return ResourceManager.GetString("VideoSurveillance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАПУСКАЕТСЯ.
        /// </summary>
        public static string WarmingUpText {
            get {
                return ResourceManager.GetString("WarmingUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XLS Документ (*.xls)|*.xls.
        /// </summary>
        public static string XLSFilter {
            get {
                return ResourceManager.GetString("XLSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XLSX Документ (*.xlsx)|*.xlsx.
        /// </summary>
        public static string XLSXFilter {
            get {
                return ResourceManager.GetString("XLSXFilter", resourceCulture);
            }
        }
    }
}
